[repository]
# Directory path for vault
vault_home = './vault'

# Directory path for daily workspace
workspace_home = './workspace'

# Directory path for workspace template.
# Files in this dir will be copied each time for a problem workspace is created.
workspace_template = './template'

[expander.cpp]
header_search_dirs = [
  "./include",
]
expansion_targets = [
  "armkn/**/*.hpp"
]
expansion_ignores = []

[test]
shell = '/bin/sh'
include = '[mM]ain.*'
compile_before_run = true
stdout_capture_max_bytes = 4096
stderr_capture_max_bytes = 4096

[[test.command]]
pattern = '*.cpp'
compile = 'make build/cpp/debug'
run = './a.out'

[[test.command]]
pattern = '*.py'
run = 'python3 #{fileName}'

[submit]
run_test = true
apply_expander = true

# Submission prgramming languages.
# Available lang name can be found by executing
#   `kpr langs atcoder`
[submit.lang]
atcoder = [
  { pattern = '*.cpp', lang = 'C++ (GCC 9.2.1)' },
  { pattern = '*.py', lang = 'PyPy3 (7.3.0)' },
]
